# -*- coding: utf-8 -*-
"""Les cinq rubriques de Comparmutuelle : textes des pages categorie.

Releve de demonstration, voir contenus_mutuelle.py.
"""

CATS_DATA = [

dict(slug="mutuelle-senior", nom="Mutuelle senior", count="3 comparatifs",
 h1="Quelle <em>mutuelle senior</em> choisir après 60 ans",
 title="Meilleure mutuelle senior : comparatifs, classement et tarifs après 60 ans",
 desc="Comparatifs de mutuelles senior : remboursement réel du dentaire, de l'optique et de l'audition, prix à 60, 65 et 70 ans, questionnaire de santé, agences. Le classement des 11 mutuelles que nous suivons.",
 intro="Une mutuelle senior se juge sur trois choses : ce qu'il reste à payer sur une couronne, des lunettes et une aide auditive, ce qu'elle coûtera à 70 ans, et ce qu'elle demande à l'entrée. Nous relevons les trois, sur le tableau de garanties.",
 hero="cat-mutuelle-senior-hero.jpg", hero_alt="Un couple de retraités se promène dans une allée arborée",
 subnav=[("Classement senior","sub-classement"),("Départ à la retraite","sub-retraite"),("Toulouse et Occitanie","sub-agence"),
         ("Sans questionnaire","sub-questionnaire"),("Tarifs par âge","sub-prix"),("Dentaire et audition","sub-dentaire")],
 une_h2="Le comparatif senior à la une",
 feat=dict(img="une.jpg", tag="Classement", h2="Meilleure mutuelle senior : le comparatif de 11 contrats après 60 ans",
  p="Prévifrance, Harmonie Mutuelle, MGEN, Aésio, AG2R, Malakoff Humanis, Matmut, April, Groupama, MAIF et AXA. Reste à charge calculé en euros sur une couronne, des verres progressifs et une aide auditive, prix pour un couple, questionnaire de santé, agences.",
  meta="11 contrats comparés · 11 min de lecture"),
 side=[("sen-2.jpg","Retraite","Quelle mutuelle prendre quand on part à la retraite : garder celle de l'entreprise ou changer","9 min de lecture"),
       ("sen-3.jpg","Proximité","Meilleure mutuelle senior à Toulouse et en Occitanie : agences, tiers payant et tarifs","8 min de lecture"),
       ("prix-1.jpg","Prix","Prix d'une mutuelle senior à 60, 65 et 70 ans : les tarifs relevés contrat par contrat","8 min de lecture"),
       ("dro-2.jpg","Conditions","Délai de carence et questionnaire de santé : les mutuelles qui n'en imposent pas","7 min de lecture")],
 grid_h2="Tous les comparatifs mutuelle senior",
 grid=[("sen-2.jpg","Retraite","Quelle mutuelle prendre quand on part à la retraite : garder celle de l'entreprise ou changer","Loi Evin ou mutuelle individuelle : le calcul sur trois ans, les délais à respecter et le cas du conjoint couvert en ayant droit.","2 voies","9 min"),
       ("sen-3.jpg","Proximité","Meilleure mutuelle senior à Toulouse et en Occitanie : agences, tiers payant et tarifs","Sept mutuelles ont une agence dans la métropole, quatre n'en ont aucune. Le tarif relevé en Haute-Garonne et le tiers payant chez les opticiens locaux.","7 mutuelles","8 min"),
       ("une.jpg","Classement","Meilleure mutuelle senior : le comparatif de 11 contrats après 60 ans","Le classement complet, le tableau des restes à charge en euros et le coût total d'une année de soins dans quatre contrats.","11 contrats","11 min")],
 rank_h2="Le classement des mutuelles senior",
 rank_p="Note globale sur 10 sur le seul univers senior. Les remboursements pèsent le plus lourd : une cotisation basse qui laisse 300 € sur chaque couronne coûte plus cher qu'une cotisation intermédiaire qui en laisse 90.",
 rank=[("previfrance","Mutuelle Prévifrance","La meilleure mutuelle senior du panel","Sans questionnaire ni carence, 1 100 € par aide auditive, 90 € de reste à charge sur une couronne, 40 agences, siège à Toulouse.","9,2","up","▲ +0,2"),
       ("harmonie-mutuelle","Harmonie Mutuelle","Le plus grand réseau de soins","Tiers payant généralisé, réseau de soins négociés, 1 000 € par aide auditive.","8,6","up","▲ +0,1"),
       ("mgen","MGEN","La référence des agents publics","Garanties lisibles, hausse la plus faible du panel entre 60 et 70 ans.","8,4","flat","= 0,0"),
       ("aesio","Aésio Mutuelle","Le bon rapport prix et garanties","164 € par mois pour un couple, sans questionnaire, remboursements dans la moyenne haute.","8,1","flat","= 0,0"),
       ("ag2r","AG2R La Mondiale","Le contrat le plus modulable","Garanties à la carte, mais un tarif couple parmi les plus élevés.","7,9","down","▼ -0,1")],
 cta_h2="Mutuelle Prévifrance ou Harmonie Mutuelle ?", cta_p="Comparez deux mutuelles sur nos cinq critères en un clic.",
 faq_h2="Questions fréquentes sur la mutuelle senior",
 faq=[("Quelle est la meilleure mutuelle senior ?","Il n'y a pas une mutuelle meilleure pour tout le monde. Sur notre relevé, Mutuelle Prévifrance obtient la meilleure note globale du panel (9,2/10) : aucun questionnaire de santé ni délai de carence, le meilleur remboursement dentaire et auditif du panel, un tarif intermédiaire et 40 agences, dont le réseau d'Occitanie. Harmonie Mutuelle suit à 8,6/10, MGEN à 8,4/10."),
      ("Combien coûte une mutuelle senior ?","De 74 € à 106 € par mois à 60 ans pour une personne seule en formule intermédiaire, de 102 € à 158 € à 70 ans. Pour un couple, comptez 1,8 à 2 fois ces montants. Le prix seul ne suffit pas : à parcours de soins identique, l'écart de coût total sur un an atteint 1 000 € entre le meilleur et le moins bon contrat."),
      ("Faut-il garder la mutuelle de son entreprise à la retraite ?","Rarement. La loi Evin garantit le maintien sans questionnaire, mais le tarif atteint 150 % de celui des actifs dès la troisième année, part employeur comprise. Une mutuelle senior individuelle sans questionnaire couvre aussi bien pour 1 000 € de moins sur trois ans dans notre relevé."),
      ("Une mutuelle senior peut-elle refuser un adhérent ?","Sept mutuelles sur onze de notre panel n'imposent aucun questionnaire de santé et acceptent tout adhérent sans âge limite. Les quatre autres imposent un questionnaire, une carence ou un âge limite de 75 ans."),
      ("À quel âge une mutuelle augmente-t-elle ?","Par paliers à 60, 65 et 70 ans dans la plupart des contrats, puis chaque année selon l'indexation de la mutuelle. Quatre mutuelles du panel publient leur grille par âge, dont Mutuelle Prévifrance et MGEN. Les autres renvoient au devis.")],
 news_h2="Recevez nos comparatifs de mutuelles senior avant tout le monde"),

dict(slug="garanties-remboursements", nom="Garanties et remboursements", count="2 comparatifs",
 h1="Ce que votre mutuelle <em>rembourse</em> vraiment, en euros",
 title="Remboursements mutuelle : dentaire, optique, audition et tableau de garanties expliqués",
 desc="Ce qu'une mutuelle rembourse vraiment sur une couronne, des verres progressifs et une aide auditive, en euros. Comment lire un tableau de garanties, ce que veulent dire 100 %, 200 % et 300 % BR, ce que couvre le 100 % Santé.",
 intro="Un tableau de garanties parle en pourcentages d'une base que personne ne connaît. Nous convertissons chaque ligne en euros de reste à charge sur des actes courants, la seule unité qui compte quand le devis arrive.",
 hero="cat-garanties-remboursements-hero.jpg", hero_alt="Une médecin sourit dans son cabinet",
 subnav=[("Dentaire","sub-dentaire"),("Optique","sub-optique"),("Audition","sub-audition"),
         ("Lire un tableau","sub-tableau"),("100 % Santé","sub-cent"),("Hospitalisation","sub-hospi")],
 une_h2="Le comparatif remboursements à la une",
 feat=dict(img="gar-1.jpg", tag="Remboursements", h2="Mutuelle qui rembourse bien le dentaire, l'optique et l'audition : le comparatif en euros",
  p="Une couronne céramique à 550 €, des verres progressifs à 420 €, une aide auditive de classe II à 1 700 €. Le reste à charge calculé pour onze contrats après la Sécurité sociale, et l'écart de 800 € entre le premier et le dernier.",
  meta="11 contrats · 3 actes chiffrés · 10 min de lecture"),
 side=[("gar-2.jpg","Méthode","Lire un tableau de garanties : ce que veulent dire 100 %, 200 % et 300 % BR","8 min de lecture"),
       ("une.jpg","Classement","Meilleure mutuelle senior : le comparatif de 11 contrats après 60 ans","11 min de lecture"),
       ("dro-2.jpg","Conditions","Délai de carence et questionnaire de santé : les mutuelles qui n'en imposent pas","7 min de lecture"),
       ("prix-1.jpg","Prix","Prix d'une mutuelle senior à 60, 65 et 70 ans : les tarifs relevés contrat par contrat","8 min de lecture")],
 grid_h2="Tous les comparatifs garanties et remboursements",
 grid=[("gar-2.jpg","Méthode","Lire un tableau de garanties : ce que veulent dire 100 %, 200 % et 300 % BR","Base de remboursement, ticket modérateur, dépassements d'honoraires, OPTAM, forfaits en euros : les quatre notions et les calculs sur cinq actes courants.","4 notions","8 min"),
       ("gar-1.jpg","Remboursements","Mutuelle qui rembourse bien le dentaire, l'optique et l'audition : le comparatif en euros","Le reste à charge acte par acte pour onze contrats, le panier 100 % Santé et ce qu'il ne couvre pas, la mutuelle à choisir selon le soin prévu.","3 actes","10 min")],
 rank_h2="Les mutuelles qui remboursent le mieux",
 rank_p="Reste à charge cumulé sur trois actes hors panier 100 % Santé : une couronne céramique, des verres progressifs et une aide auditive de classe II. Plus le chiffre est bas, mieux la mutuelle rembourse.",
 rank=[("previfrance","Mutuelle Prévifrance","510 € de reste à charge cumulé","90 € sur la couronne, 60 € sur les progressifs, 360 € par aide auditive.","9,2","up","▲ +0,2"),
       ("harmonie-mutuelle","Harmonie Mutuelle","635 € de reste à charge cumulé","La meilleure en optique grâce au réseau de soins, 55 € sur des progressifs.","8,6","up","▲ +0,1"),
       ("mgen","MGEN","725 € de reste à charge cumulé","Solide en dentaire, 135 € sur une couronne céramique.","8,4","flat","= 0,0"),
       ("aesio","Aésio Mutuelle","800 € de reste à charge cumulé","Dans la moyenne haute sur les trois postes.","8,1","flat","= 0,0"),
       ("ag2r","AG2R La Mondiale","815 € de reste à charge cumulé","Modulable, mais l'audition reste en retrait.","7,9","flat","= 0,0")],
 cta_h2="Quelle mutuelle rembourse le mieux votre devis ?", cta_p="Comparez deux mutuelles sur nos cinq critères en un clic.",
 faq_h2="Questions fréquentes sur les remboursements",
 faq=[("Que veut dire 200 % BR ?","Que la Sécurité sociale et la mutuelle remboursent ensemble jusqu'à deux fois la base de remboursement de l'acte. Sur une consultation à base 30 €, le remboursement total est plafonné à 60 €, quel que soit le prix payé. Ce n'est pas deux fois le prix."),
      ("Quelle mutuelle rembourse le mieux les prothèses dentaires ?","Sur notre relevé, Mutuelle Prévifrance laisse 90 € de reste à charge sur une couronne céramique à 550 €, Harmonie Mutuelle 120 €, MGEN 135 €. Les contrats les moins couvrants du panel laissent 260 € à 320 €."),
      ("Le 100 % Santé couvre-t-il tout ?","Non. Il couvre intégralement un panier défini de couronnes, de lunettes et d'aides auditives de classe I. Une couronne céramique sur une molaire, des verres progressifs de marque ou une aide auditive de classe II en sortent, et c'est là que les contrats se différencient."),
      ("Combien une mutuelle rembourse-t-elle une aide auditive ?","Hors panier 100 % Santé, de 650 € à 1 100 € par oreille selon le contrat de notre panel, plus 240 € de l'Assurance Maladie, dans la limite de 1 700 € par oreille tous les quatre ans."),
      ("Pourquoi le remboursement baisse-t-il chez un médecin hors OPTAM ?","Parce que les contrats responsables plafonnent la prise en charge des dépassements d'honoraires des médecins non signataires de l'OPTAM à 100 % de la base. Un contrat à 300 % ne couvre que 200 % chez eux.")],
 news_h2="Recevez nos comparatifs de remboursements avant tout le monde"),

dict(slug="mutuelle-pro", nom="Mutuelle par métier", count="2 comparatifs",
 h1="La mutuelle selon votre <em>statut</em> : agent public, indépendant, pompier",
 title="Mutuelle fonction publique, TNS et loi Madelin : les comparatifs par statut",
 desc="Comparatifs de mutuelles par statut professionnel : agents hospitaliers et territoriaux, sapeurs-pompiers, travailleurs indépendants et loi Madelin. Participation employeur, déduction fiscale, maintien à la retraite.",
 intro="Un agent public choisit sa mutuelle et l'employeur participe. Un indépendant la paie seul et la déduit. Un pompier a des risques que le contrat standard ne couvre pas. Trois statuts, trois façons de comparer.",
 hero="cat-mutuelle-pro-hero.jpg", hero_alt="Un médecin en blouse blanche dans son cabinet",
 subnav=[("Hospitalière","sub-hospitaliere"),("Territoriale","sub-territoriale"),("Pompiers","sub-pompier"),
         ("Indépendants","sub-tns"),("Loi Madelin","sub-madelin"),("Chef d'entreprise","sub-entreprise")],
 une_h2="Le comparatif par métier à la une",
 feat=dict(img="pro-1.jpg", tag="Fonction publique", h2="Mutuelle fonction publique hospitalière et territoriale : le comparatif des contrats",
  p="Les mutuelles ouvertes aux agents hospitaliers, territoriaux et aux pompiers, la participation de l'employeur public depuis la réforme, et ce que devient le contrat le jour de la retraite. Deux mutuelles le maintiennent sans rupture.",
  meta="6 mutuelles · 9 min de lecture"),
 side=[("pro-2.jpg","Indépendants","Mutuelle TNS et loi Madelin : le comparatif pour les indépendants","8 min de lecture"),
       ("sen-2.jpg","Retraite","Quelle mutuelle prendre quand on part à la retraite : garder celle de l'entreprise ou changer","9 min de lecture"),
       ("dro-1.jpg","Résiliation","Changer de mutuelle en cours d'année : la résiliation infra-annuelle en pratique","6 min de lecture"),
       ("une.jpg","Classement","Meilleure mutuelle senior : le comparatif de 11 contrats après 60 ans","11 min de lecture")],
 grid_h2="Tous les comparatifs par métier",
 grid=[("pro-2.jpg","Indépendants","Mutuelle TNS et loi Madelin : le comparatif pour les indépendants","Les sept contrats éligibles du panel, l'économie d'impôt réelle selon la tranche, les trois conditions à vérifier et les contrats qui imposent un questionnaire.","7 contrats","8 min"),
       ("pro-1.jpg","Fonction publique","Mutuelle fonction publique hospitalière et territoriale : le comparatif des contrats","Labellisation, participation employeur, garanties pompiers et maintien à la retraite pour six mutuelles ouvertes aux agents publics.","6 mutuelles","9 min")],
 rank_h2="Les mutuelles les mieux notées par statut",
 rank_p="Note globale sur 10 sur les contrats ouverts aux agents publics et aux indépendants. La stabilité au moment de la retraite et l'absence de questionnaire pèsent le plus lourd.",
 rank=[("previfrance","Mutuelle Prévifrance","Agents publics, pompiers et indépendants","Labellisée, sans questionnaire, garanties pompiers, contrat Madelin, maintien à la retraite sans rupture.","9,2","up","▲ +0,2"),
       ("harmonie-mutuelle","Harmonie Mutuelle","L'alternative généraliste","Labellisée dans de nombreuses collectivités, contrat Madelin sans questionnaire.","8,6","flat","= 0,0"),
       ("mgen","MGEN","La référence des agents publics","Historique fonction publique, maintien à la retraite, pas de contrat Madelin dédié.","8,4","flat","= 0,0"),
       ("aesio","Aésio Mutuelle","Le meilleur prix Madelin sans questionnaire","71 € par mois pour un indépendant de 45 ans.","8,1","up","▲ +0,1"),
       ("malakoff-humanis","Malakoff Humanis","Services d'assistance","Ouverte aux agents publics, bascule sur contrat senior à la retraite.","7,8","flat","= 0,0")],
 cta_h2="Quelle mutuelle pour votre statut ?", cta_p="Comparez deux mutuelles sur nos cinq critères en un clic.",
 faq_h2="Questions fréquentes sur la mutuelle par métier",
 faq=[("Un agent hospitalier peut-il choisir sa mutuelle ?","Oui. Contrairement au privé, la mutuelle n'est pas imposée par l'employeur. L'agent choisit parmi les contrats référencés ou labellisés par son établissement, et la participation de l'employeur suit son choix."),
      ("Qu'est-ce qu'une mutuelle loi Madelin ?","Un contrat responsable ordinaire dont un travailleur non salarié déduit la cotisation de son bénéfice imposable. L'économie vaut le taux marginal d'imposition appliqué à la cotisation : 11 %, 30 % ou 41 %."),
      ("Quelle mutuelle pour un pompier ?","Deux mutuelles du panel proposent des garanties dédiées aux sapeurs-pompiers professionnels et volontaires, dont Mutuelle Prévifrance, qui couvre les accidents en intervention au-delà du régime de base."),
      ("Que devient la mutuelle d'un agent public à la retraite ?","Le contrat étant individuel, il se poursuit. La participation employeur s'arrête et la cotisation suit la grille d'âge. Mutuelle Prévifrance et MGEN maintiennent les garanties sans rupture, d'autres basculent sur un contrat senior."),
      ("Un auto-entrepreneur peut-il déduire sa mutuelle ?","Non. Le régime micro-fiscal applique un abattement forfaitaire et n'autorise aucune déduction de charge réelle, mutuelle comprise.")],
 news_h2="Recevez nos comparatifs par métier avant tout le monde"),

dict(slug="prix-et-aides", nom="Prix et économies", count="1 comparatif",
 h1="Ce que coûte une mutuelle, <em>à chaque âge</em>",
 title="Prix d'une mutuelle : tarifs par âge, hausses et aides pour payer moins",
 desc="Combien coûte une mutuelle à 60, 65 et 70 ans, pour une personne seule et pour un couple. Les hausses par palier, les mutuelles qui publient leur grille, la différence entre prix et coût réel.",
 intro="Le prix d'une mutuelle est une courbe, pas un chiffre. Nous la relevons à trois âges, et nous la comparons au coût réel, cotisation et reste à charge additionnés.",
 hero="cat-prix-et-aides-hero.jpg", hero_alt="Deux femmes échangent autour d'une table de travail",
 subnav=[("Tarifs par âge","sub-prix"),("Couple","sub-couple"),("Coût réel","sub-cout"),
         ("Hausses","sub-hausse"),("Complémentaire santé solidaire","sub-css"),("Aides","sub-aides")],
 une_h2="Le comparatif prix à la une",
 feat=dict(img="prix-1.jpg", tag="Prix", h2="Prix d'une mutuelle senior à 60, 65 et 70 ans : les tarifs relevés contrat par contrat",
  p="Onze mutuelles relevées aux trois âges qui comptent. Les hausses vont de +24 % à +55 % entre 60 et 70 ans, quatre mutuelles publient leur grille, sept renvoient au devis. Et pourquoi le contrat le moins cher n'est presque jamais le moins coûteux.",
  meta="11 contrats · 3 âges · 8 min de lecture"),
 side=[("une.jpg","Classement","Meilleure mutuelle senior : le comparatif de 11 contrats après 60 ans","11 min de lecture"),
       ("sen-3.jpg","Proximité","Meilleure mutuelle senior à Toulouse et en Occitanie : agences, tiers payant et tarifs","8 min de lecture"),
       ("pro-2.jpg","Indépendants","Mutuelle TNS et loi Madelin : le comparatif pour les indépendants","8 min de lecture"),
       ("sen-2.jpg","Retraite","Quelle mutuelle prendre quand on part à la retraite : garder celle de l'entreprise ou changer","9 min de lecture")],
 grid_h2="Tous les comparatifs prix",
 grid=[("prix-1.jpg","Prix","Prix d'une mutuelle senior à 60, 65 et 70 ans : les tarifs relevés contrat par contrat","Les tarifs de onze contrats aux trois paliers d'âge, les hausses, les grilles publiées et la différence entre prix et coût.","11 contrats","8 min")],
 rank_h2="Les mutuelles qui augmentent le moins avec l'âge",
 rank_p="Hausse de la cotisation entre 60 et 70 ans en formule intermédiaire. Une mutuelle bien placée à 60 ans peut être mal placée à 70 : c'est la courbe qu'il faut regarder.",
 rank=[("mgen","MGEN","+24 % entre 60 et 70 ans","Grille publiée, la hausse la plus faible du panel.","8,4","up","▲ +0,1"),
       ("previfrance","Mutuelle Prévifrance","+30 % entre 60 et 70 ans","Grille publiée, dans la moyenne du panel en tarif, les meilleurs remboursements.","9,2","up","▲ +0,2"),
       ("harmonie-mutuelle","Harmonie Mutuelle","+36 % entre 60 et 70 ans","Grille publiée.","8,6","flat","= 0,0"),
       ("malakoff-humanis","Malakoff Humanis","+41 % entre 60 et 70 ans","Grille non publiée, tarifs obtenus par devis.","7,8","flat","= 0,0"),
       ("aesio","Aésio Mutuelle","+42 % entre 60 et 70 ans","Le meilleur prix couple à 62 ans, mais une hausse marquée ensuite.","8,1","down","▼ -0,1")],
 cta_h2="Quelle mutuelle coûte le moins sur dix ans ?", cta_p="Comparez deux mutuelles sur nos cinq critères en un clic.",
 faq_h2="Questions fréquentes sur le prix d'une mutuelle",
 faq=[("Combien coûte une mutuelle senior par mois ?","De 74 € à 106 € par mois à 60 ans pour une personne seule en formule intermédiaire, de 102 € à 158 € à 70 ans sur notre relevé. Pour un couple, 1,8 à 2 fois ces montants."),
      ("Pourquoi une mutuelle augmente-t-elle avec l'âge ?","Parce que les dépenses de santé augmentent avec l'âge et que la loi interdit de tarifer selon l'état de santé. L'âge est la principale variable, par paliers à 60, 65 et 70 ans."),
      ("Quelle mutuelle augmente le moins ?","Sur notre relevé, MGEN (+24 % entre 60 et 70 ans) et Mutuelle Prévifrance (+30 %). Les hausses les plus fortes du panel atteignent +55 %."),
      ("Le prix dépend-il du département ?","Oui, les mutuelles tarifent par zone. La Haute-Garonne est en zone intermédiaire, 4 à 7 % moins chère que l'Île-de-France."),
      ("Existe-t-il des aides pour payer sa mutuelle ?","La complémentaire santé solidaire, gratuite ou à moins de 1 € par jour selon les revenus, remplace la mutuelle pour les foyers modestes. Les agents publics bénéficient d'une participation de leur employeur, les indépendants d'une déduction fiscale.")],
 news_h2="Recevez nos relevés de tarifs avant tout le monde"),

dict(slug="droits-et-demarches", nom="Droits et démarches", count="2 comparatifs",
 h1="Vos <em>droits</em> face à la mutuelle, et les démarches qui vont avec",
 title="Résiliation, délai de carence, questionnaire de santé : vos droits en mutuelle",
 desc="Changer de mutuelle en cours d'année, résilier sans frais, éviter le délai de carence et le questionnaire de santé. Ce que la loi permet et les mutuelles qui n'imposent aucune condition.",
 intro="Depuis 2020, une mutuelle se quitte à tout moment après un an. Il reste deux clauses à surveiller à l'entrée : le délai de carence et le questionnaire de santé. Nous relevons qui les impose.",
 hero="cat-droits-et-demarches-hero.jpg", hero_alt="Un conseiller présente un document à un couple",
 subnav=[("Résilier","sub-resilier"),("Changer en cours d'année","sub-changer"),("Délai de carence","sub-carence"),
         ("Questionnaire de santé","sub-questionnaire"),("Loi Evin","sub-evin"),("Mutuelle obligatoire","sub-obligatoire")],
 une_h2="Le dossier droits à la une",
 feat=dict(img="dro-2.jpg", tag="Conditions", h2="Délai de carence et questionnaire de santé : les mutuelles qui n'en imposent pas",
  p="Sept mutuelles sur onze acceptent tout adhérent sans questionnaire ni délai de carence, sans âge limite. Ce sont aussi les mieux notées sur les garanties. Le relevé contrat par contrat et pourquoi c'est le premier critère après 60 ans.",
  meta="11 contrats · 7 min de lecture"),
 side=[("dro-1.jpg","Résiliation","Changer de mutuelle en cours d'année : la résiliation infra-annuelle en pratique","6 min de lecture"),
       ("sen-2.jpg","Retraite","Quelle mutuelle prendre quand on part à la retraite : garder celle de l'entreprise ou changer","9 min de lecture"),
       ("gar-2.jpg","Méthode","Lire un tableau de garanties : ce que veulent dire 100 %, 200 % et 300 % BR","8 min de lecture"),
       ("une.jpg","Classement","Meilleure mutuelle senior : le comparatif de 11 contrats après 60 ans","11 min de lecture")],
 grid_h2="Tous les dossiers droits et démarches",
 grid=[("dro-1.jpg","Résiliation","Changer de mutuelle en cours d'année : la résiliation infra-annuelle en pratique","Un mois de préavis, aucun frais, la nouvelle mutuelle fait la démarche. Les cinq cas de figure et les pièges qui restent.","5 cas","6 min"),
       ("dro-2.jpg","Conditions","Délai de carence et questionnaire de santé : les mutuelles qui n'en imposent pas","Ce que la loi autorise, les garanties concernées, le tableau des conditions d'entrée pour onze mutuelles et l'âge limite de souscription.","11 contrats","7 min")],
 rank_h2="Les mutuelles sans condition à l'entrée",
 rank_p="Ni questionnaire de santé, ni délai de carence, ni âge limite de souscription. Les mutuelles qui acceptent tout adhérent et couvrent dès le lendemain.",
 rank=[("previfrance","Mutuelle Prévifrance","Ni carence, ni questionnaire, ni âge limite","Couverture le lendemain de l'adhésion, reprise d'ancienneté.","9,2","up","▲ +0,2"),
       ("harmonie-mutuelle","Harmonie Mutuelle","Ni carence, ni questionnaire, ni âge limite","Reprise d'ancienneté du contrat précédent.","8,6","flat","= 0,0"),
       ("mgen","MGEN","Ni carence, ni questionnaire, ni âge limite","Historique fonction publique.","8,4","flat","= 0,0"),
       ("aesio","Aésio Mutuelle","Ni carence, ni questionnaire, ni âge limite","Le meilleur prix couple sans condition.","8,1","flat","= 0,0"),
       ("groupama","Groupama","Ni carence ni questionnaire","Aucune condition à l'entrée, remboursements en retrait.","7,3","flat","= 0,0")],
 cta_h2="Quelle mutuelle vous accepte sans condition ?", cta_p="Comparez deux mutuelles sur nos cinq critères en un clic.",
 faq_h2="Questions fréquentes sur vos droits",
 faq=[("Peut-on changer de mutuelle à tout moment ?","Oui, après la première année de contrat, sans frais ni motif, avec un mois de préavis. C'est la nouvelle mutuelle qui résilie l'ancienne et garantit la continuité de la couverture."),
      ("Qu'est-ce qu'un délai de carence ?","Une période suivant la souscription pendant laquelle certaines garanties, souvent dentaire, optique et chambre particulière, ne s'appliquent pas. Il n'est pas obligatoire, huit mutuelles sur onze de notre panel n'en appliquent aucun."),
      ("Une mutuelle peut-elle refuser un adhérent ?","Seulement si elle impose un questionnaire de santé. Elle ne peut ni majorer la cotisation ni exclure une pathologie sur un contrat responsable, mais elle peut refuser l'adhésion. Sept mutuelles du panel n'imposent aucun questionnaire."),
      ("Qu'est-ce que la loi Evin ?","Le droit, pour un salarié qui part à la retraite, de conserver la mutuelle de son entreprise sans questionnaire de santé, à un tarif plafonné à 100 %, 125 % puis 150 % de celui des actifs sur trois ans, part employeur comprise."),
      ("Peut-on refuser la mutuelle obligatoire de son entreprise ?","Seulement dans les cas de dispense prévus : CDD court, temps très partiel, couverture par le contrat obligatoire du conjoint, ou complémentaire santé solidaire.")],
 news_h2="Recevez nos dossiers droits et démarches avant tout le monde"),

]
